### PR TITLE
Add ability to show progress bars

### PR DESCRIPTION
**Pull request by hyanwong**
Converting a large tree sequence was taking a long time, so I added a "progress" option, so that when importing from a tree sequence it is (optionally) possible to show progress bars.

It appears as if the code that iterates over sites is quite slow:. I'm getting 40000 iterations/s when importing edges from a large ARG, and 900000 iterations/s when importing nodes, but only 48 it/s when importing sites. 

I can attach the large ARG we are using (only 29407 sites, though), but I'm guessing the reason for the slowness is obvious.

### CODE REVIEW

**Comment by hyanwong** [comment]
Did you figure out any way to speed up reading in the sites, @kitchensjn ?

**Comment by kitchensjn** [comment]
Thanks for adding that! Helpful for benchmarking.

```
edges_output.loc[edges_output["id"] == edge_id_reference[mut.edge], "mutation_count"] += 1
```

is inefficient in the loop. Handling this in a different way brings the sites conversion back up to speed. 45f2ff3 is a hot fix for this on the mutations branch. Though, there's definitely more room for improvement - deferring some calculations to draw and probably reducing some redundant storage of information between tables.

**Comment by hyanwong** [comment]
Great, thanks for looking into this. It was going to take almost an hour to convert my tree sequence file before.

I note, by the way, that I forgot to put a tqdm wrapper on line 451 (`for edge in mutation_counts:`), and now this is the line which is taking the most time (about 6 mins on my ARG). I guess the progress bar should be added there, but I also wonder if there's a way to speed that up too?

**Comment by kitchensjn** [comment]
You should be able to comment out that loop entirely actually. I was keeping track of mutation counts per edge for an alternate mutation styling but we aren't using it for anything currently. This is also one of the instances where that information isn't really needed in the edges table and those values could just be calculated on draw for the subset of edges being plotted if we want it. So I'll rethink this part!

**Pull request merged**
